### ISSUE TITLE
Debugging errors

### ISSUE THREAD

**Issue by snwfdhmp** [drkaka/kkpanic#1]
### You should not use panic(err)

https://github.com/drkaka/kkpanic/blob/235deec21382479abe533d4c03980e073991e865/kkpanic.go#L4-L8

Hey dude,

Just a friendly advice. Use [error logging package like this](https://github.com/snwfdhmp/errlog) for debugging your errors. Debug your code with :

1. Clear stack trace
2. Failing func call highlighting

Real better than panic-ing (in most case). You can still force exit if you need it.

<img width="999" alt="example" src="https://user-images.githubusercontent.com/23099246/53098953-11310c80-3525-11e9-8f6f-302791743cdf.png">

It’s way more easier then to debug. I would be happy to get your feedbacks.

**Comment by kakaLQY** [comment]
@snwfdhmp Thanks for your comments. I didn't imagined that some one would leave a comment for this so simple Repo, which I used to wrap the code in some use cases years ago.  
 
I didn't try but took a look at your Repo, which seems quite different from my purpose in this Repo. But anyway for example [this block](https://github.com/snwfdhmp/errlog/blob/65ed3d280c2c0961d9a66c0f5250743efbd333fa/logger.go#L111-L114) depends on GOPATH, I am wondering whether this will support [go Modules](https://github.com/golang/go/wiki/Modules). And [read file](https://github.com/snwfdhmp/errlog/blob/65ed3d280c2c0961d9a66c0f5250743efbd333fa/logger.go#L116), personally I think is a little heavy. And stack tracing with `panic` for me is very enough, if to log things I prefer [zap](https://github.com/uber-go/zap). 

But anyway, wish your's can work well for the purpose and be optimized better and better. 
Cheers.

**Comment by snwfdhmp** [comment]
@kakaLQY thank you for your nice reply and your feedbacks !

I would likely answer all of your remarks, but have understood that you're not actually looking for a such solution. Tell me if you're interested anyway.
Thank you for your links, very good references.
